language: node_js
node_js:
- node
addons:
  sauce_connect:
    username: paperhive
  jwt:
    secure: 3SxC13yRSZjYoLUv+dPQFaht73S81rlW8jz9XEZnmDVnpZbnzNvnM9GlOSiijzBEwunzLEWTJ2V1wlKBw1fdjgjBn1v99FAKu4OHmf7qi9O+GZH5Z/+OsCpWglx+Dbq+XC5W0YhGZAtfIEdQXW3hY1IWGiHof/hbsMNvYfmBkGCD0TI/HwJvfq8XVSWIS4QaH6fIRFtA0A+yU2TPMDGBH35AM3nWrdN665US8aGM8vH1xCF8RdrqCVc0lnFV6e7me9Gd5BPKuCXuQa9O8rsG3WSeCGh2NnJ3y2d2h2X4Dbvl/GB7kSGWnCxsTIWfKhae1XGh2x2uhEf2VytB1x5/JYgN15g2UUYFvPY8+dYFtqtGok7mWhTYN4gMQVfGYsufbhFtCUmUV00y8e/GWaov9ea3lwt1ZAiOjV5zbB6jlLcfXSEHRwyCmx/38NnoqI/zWxOvs3OjcCwgov9LFGrHzUsygrqGCwtHet+sAPg5e+/Nc2SUVedkbM5A/tIGYoKtJEAJyU3Wr32vNj+cjrQTe8P6yfUz9Nx2rlOoiELK3cumdBEEbPVpqCQf/P3HN1lo04Bddhz8cGrA5IQt/sC/dZDGgNFelOucHn/B5EqHXvXeuyeuc5JvdbajKzQhxWqdx+ZIQqXf+aRPFEzjkR9DhAswuhcj4WTluttX5538z/g=
script:
- npm run build
- npm run test
- npm run e2e
