language: node_js
node_js:
  - node
sudo: required
services:
  - docker
addons:
  sauce_connect:
    username: paperhive
  jwt:
    secure: "uKlR70ccu1tljEvyvqpIX7yM76xnN8hIEjC/sK00xCu7FIxhVtoOMbqeojLdgDlpxH6uo6nrE6OiGnzzIbeSx/ybyyRxWr7gH1KaY3CVR4mkTTBoeWAShX84qpwqOUFz250usdcxYeYzm/xJoyiNTey9mZPr+4nWa9UFaDP2XfiElq2rv1psw3u0aK8A/Z7tjDfkpkmVsq5Xa8Q+HI7kiGtCAopBUPQyNZYr/kOeL5xmMJla6OeKt1iV9W5+jWPAG0WlLfS59rJ8u9rvIlxe4iPCx4Lev3vIwWWDcz6hmZoeNWr4LTOBFZBX5H4S5fSpxc5ZAN9xhyENpX0CYKIkxaWjKXTWDwl7IA7iga9p1/B4QMf6em/UGAlufvwBdP3ztHxnhXg5FtaoN9mvUONo6fS8C0Y+atjxOggIPSBw15BW+dQ38VLh9fyCiq2wL7SP3iTuRJ6JHP44Qm4QT2GS047t7M41koSo4RmLCqWtVWmeRW8qcyz56sTUo97D5KLK549uRvAvlEIA5imcp2aGl0KOWWtDjht6ISEKAfu96LiDOCOe3hC0puFU0o6G21fVL7V+rJf89yu+jdES+oSyo7gnFkFP+OdLr4xGPiiCa28X409x9m/P4VtcSwRqh2OBJcXHVnakNkqiq6JDYjCLdoubokyHLjxIESIfGw+ctnw="
script:
  - npm run build
  - npm run test
  - npm run e2e
